// Generated by CoffeeScript 1.10.0
(function () {
    var typist;

    typist = document.querySelector("#typist-element1");

    new Typist(typist, {
        letterInterval: 60,
        textInterval: 3000
    });

    var dasQuote;

    dasQuote = document.querySelector("#DasQuote");

    new Typist(dasQuote, {
        letterInterval: 60,
        textInterval: 3000
    });

    var QQuote;

    QQuote = document.querySelector("#QuizQuote");

    new Typist(QQuote, {
        letterInterval: 60,
        textInterval: 3000
    });

}).call(this);