// Generated by CoffeeScript 1.10.0
(function() {
  var typist;

  typist = document.querySelector("#typist-element");

  new Typist(typist, {
    letterInterval: 60,
    textInterval: 3000,
    onSlide: function(text, options) {
      var suffix;
      suffix = options.typist.getAttribute("data-typist-suffix");
      return log(text + " " + suffix);
    }
  });

}).call(this);
